In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [2]:
navegador = webdriver.Chrome()

In [3]:
# abrindo o site desejado
navegador.get('https://www.detran.sp.gov.br/wps/portal/portaldetran/detran/estatisticastransito/')

In [4]:
# encontrando o elemento
navegador.find_element(By.XPATH, '//*[@id="accordiondef"]/div[3]/div[1]/a/img')

In [5]:
# clicando no elemento encontrado
navegador.find_element(By.XPATH, '//*[@id="accordiondef"]/div[3]/div[1]/a/img').click()

In [6]:
#clicando no arquivo
navegador.find_element(By.XPATH, '//*[@id="5"]/div/div[2]/div/table/tbody/tr/td[2]/table/tbody/tr[2]/td[1]/div').click()

# TRATAMENTO DOS DADOS

In [7]:
import os
import pandas as pd
import numpy as np

In [8]:
caminho_csv = os.path.join('..', '0_bases_originais', 'Multas 2021.csv')

df = pd.read_csv(caminho_csv)
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Ano: 2021,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Municipio,Nome Municipio,Enq,Descricao,janeiro,fevereiro,marco,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro,Total
1,00790,ARCO IRIS,5010-0,Dirigir veiculo sem possuir CNH/PPD/ACC,1,1,3,0,3,1,1,0,1,0,0,1,12
2,00790,ARCO IRIS,5045-0,Dirigir veiculo com validade de CNH/PPD vencid...,0,1,0,0,0,1,0,0,0,0,0,0,2
3,00790,ARCO IRIS,5061-0,Entregar veiculo a pessoa sem CNH/PPD/ACC,0,0,1,0,0,0,1,0,0,0,0,0,2
4,00790,ARCO IRIS,5118-0,Permitir posse/conducao do veiculo a pessoa se...,0,0,1,0,2,1,0,0,1,0,0,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31171,07273,VARGEM GRANDE PAULISTA,7633-1,Dirigir veiculo segurando telefone celular,2,8,6,2,7,3,1,1,3,1,2,1,37
31172,07273,VARGEM GRANDE PAULISTA,7633-2,Dirigir veiculo manuseando telefone celular,21,16,11,25,20,19,16,16,13,7,7,9,180
31173,07273,VARGEM GRANDE PAULISTA,7684-1,NaN,0,0,0,0,1,0,0,1,0,0,1,0,3
31174,07273,VARGEM GRANDE PAULISTA,7684-2,NaN,0,0,0,0,0,0,0,0,0,0,0,1,1
31175,07273,VARGEM GRANDE PAULISTA,7714-1,NaN,0,0,0,0,0,0,0,0,0,0,0,1,1

In [9]:
df = pd.read_csv(caminho_csv, header = None)

In [10]:
df= df.iloc[1:].reset_index(drop=True)

In [11]:
df.columns = df.iloc[0]

In [12]:
df

,Municipio,Nome Municipio,Enq,Descricao,janeiro,fevereiro,marco,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro,Total
0,Municipio,Nome Municipio,Enq,Descricao,janeiro,fevereiro,marco,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro,Total
1,00790,ARCO IRIS,5010-0,Dirigir veiculo sem possuir CNH/PPD/ACC,1,1,3,0,3,1,1,0,1,0,0,1,12
2,00790,ARCO IRIS,5045-0,Dirigir veiculo com validade de CNH/PPD vencid...,0,1,0,0,0,1,0,0,0,0,0,0,2
3,00790,ARCO IRIS,5061-0,Entregar veiculo a pessoa sem CNH/PPD/ACC,0,0,1,0,0,0,1,0,0,0,0,0,2
4,00790,ARCO IRIS,5118-0,Permitir posse/conducao do veiculo a pessoa se...,0,0,1,0,2,1,0,0,1,0,0,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31171,07273,VARGEM GRANDE PAULISTA,7633-1,Dirigir veiculo segurando telefone celular,2,8,6,2,7,3,1,1,3,1,2,1,37
31172,07273,VARGEM GRANDE PAULISTA,7633-2,Dirigir veiculo manuseando telefone celular,21,16,11,25,20,19,16,16,13,7,7,9,180
31173,07273,VARGEM GRANDE PAULISTA,7684-1,NaN,0,0,0,0,1,0,0,1,0,0,1,0,3
31174,07273,VARGEM GRANDE PAULISTA,7684-2,NaN,0,0,0,0,0,0,0,0,0,0,0,1,1
31175,07273,VARGEM GRANDE PAULISTA,7714-1,NaN,0,0,0,0,0,0,0,0,0,0,0,1,1

In [13]:
df = df.drop(index=0)
df

,Municipio,Nome Municipio,Enq,Descricao,janeiro,fevereiro,marco,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro,Total
1,00790,ARCO IRIS,5010-0,Dirigir veiculo sem possuir CNH/PPD/ACC,1,1,3,0,3,1,1,0,1,0,0,1,12
2,00790,ARCO IRIS,5045-0,Dirigir veiculo com validade de CNH/PPD vencid...,0,1,0,0,0,1,0,0,0,0,0,0,2
3,00790,ARCO IRIS,5061-0,Entregar veiculo a pessoa sem CNH/PPD/ACC,0,0,1,0,0,0,1,0,0,0,0,0,2
4,00790,ARCO IRIS,5118-0,Permitir posse/conducao do veiculo a pessoa se...,0,0,1,0,2,1,0,0,1,0,0,1,6
5,00790,ARCO IRIS,5193-0,Transportar crianca sem observancia das normas...,0,0,0,0,1,0,0,0,0,0,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31171,07273,VARGEM GRANDE PAULISTA,7633-1,Dirigir veiculo segurando telefone celular,2,8,6,2,7,3,1,1,3,1,2,1,37
31172,07273,VARGEM GRANDE PAULISTA,7633-2,Dirigir veiculo manuseando telefone celular,21,16,11,25,20,19,16,16,13,7,7,9,180
31173,07273,VARGEM GRANDE PAULISTA,7684-1,NaN,0,0,0,0,1,0,0,1,0,0,1,0,3
31174,07273,VARGEM GRANDE PAULISTA,7684-2,NaN,0,0,0,0,0,0,0,0,0,0,0,1,1
31175,07273,VARGEM GRANDE PAULISTA,7714-1,NaN,0,0,0,0,0,0,0,0,0,0,0,1,1

In [14]:
caminho_saida = os.path.join('..', '1_bases_tratadas', 'df_tratada.csv')
caminho_saida_upload = os.path.join('..', '3_base_de_upload', 'df_tratada.csv')

df.to_csv(caminho_saida, index= False)
df.to_csv(caminho_saida_upload, index= False)